from typing import Callable, Iterator

class _EventSlot:
    targets: list[Callable]
    __name__: str
    def __init__(self, name: str) -> None: ...
    def __call__(self, *a: object, **kw: object) -> None: ...
    def __add__(self, f: Callable) -> "_EventSlot": ...
    def __sub__(self, f: Callable) -> "_EventSlot": ...
    def __iadd__(self, f: Callable) -> "_EventSlot": ...
    def __isub__(self, f: Callable) -> "_EventSlot": ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Callable]: ...
    def __getitem__(self, key: int) -> Callable: ...

class EventsException(Exception): ...

class Events:
    def __init__(self, events: object = ..., event_slot_cls: type = ...) -> None: ...
    def __getattr__(self, name: str) -> _EventSlot: ...
    def __setattr__(self, name: str, value: _EventSlot) -> None: ...
    def __getitem__(self, item: str) -> _EventSlot: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_EventSlot]: ...
