# Checkout master, create sdist and bdist, and release to pypi

name: Release to PyPi
on:
  workflow_dispatch:
    inputs:
      pypi-target:
        description: Deploy to PyPi [Main] or [Test]
        required: true
        default: 'Main'

jobs:
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.10'
      - name: Create dist
        run: |
          python -m pip install --upgrade pip
          pip install twine build
          python -m build
      - name: Validate dist
        run: twine check dist/*
      - if: github.event.inputs.pypi-target == 'Main'
        name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
      - if: github.event.inputs.pypi-target == 'Test'
        name: Publish to Test-PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*
